### PR TITLE
Updated default wallpapers

### PR DESCRIPTION
**Pull request by hanskokx**
- Adjusted colors on all images
- Added LuneOS coffee wallpaper
- Images have been compressed with JPEGmini Pro

### CODE REVIEW

**Comment by Tofee** [comment]
It looks like butterfly.jpg is missing

**Comment by hanskokx** [comment]
I removed it, as I did not feel it reflected the quality standard we're aiming for.  It's clearly a cell phone shot, but it's blurry and pixelated.  If you believe it should remain, I'll concede, but I believe it should be removed.  

## 

Hans Kokx

**Comment by Herrie82** [comment]
If you could add the butterfly back, please do so. People might like it (don't ask me why)

**Comment by hanskokx** [comment]
Re-added the butterfly photo for you.

**Pull request merged**
